name: GitHub Proxy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Proxy
        run: |
         sudo apt update
         sudo apt install -y ssh
         ssh-keygen -t ed25519 -N "" -f /home/runner/.ssh/id_ed25519
         echo "✅ SSH key generated!"
         echo "👇 Copy this public key to your local authorized_keys file later:"
         cat /home/runner/.ssh/id_ed25519.pub
         sudo mkdir -p /run/sshd 
         sudo /usr/sbin/sshd -D &
         echo "✅ SSH Server is running on port 22"
         echo "🌍 Your Proxy IP:"
         hostname -I
         echo "🎯 Connect using this command:"
         echo "ssh -D 1080 -N -o StrictHostKeyChecking=no runner@<IP>"
  
         # حالا حلقه بی‌نهایت برای نگه داشتن Job فعال
         while true; do sleep 3600; done
